INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 27, 'Biology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 27, 'Sport');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 27, 'Law');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 27, 'Tamil Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 27, 'Art');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 27, 'Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 27, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 27, 'Design and Technology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 28, 'Business');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 28, 'Sociology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 28, 'Design');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 28, 'Computing');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 28, 'Design and Technology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 28, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 28, 'Biology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 28, 'Electronics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 29, 'Physics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 29, 'Computing');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 29, 'Humanities');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 29, 'Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 29, 'Higher Chinese');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 29, 'Art');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 29, 'Geography');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 29, 'Malay Literature');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 30, 'Nursing');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 30, 'Chemistry');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 30, 'Computing');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 30, 'Computing');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 30, 'Higher Malay');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 30, 'Biology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 30, 'Chemistry');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 30, 'Electronics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 31, 'Physics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 31, 'Literature');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 31, 'Engineering');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 31, 'Tamil Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 31, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 31, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 31, 'Physical Education');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 31, 'Literature');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 32, 'Literature');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 32, 'Biology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 32, 'Business');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 32, 'Malay Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 32, 'Elementary Mathematics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 32, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 32, 'Design and Technology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 32, 'Music');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 33, 'Nursing');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 33, 'Law');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 33, 'Chemistry');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 33, 'Chinese Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 33, 'Principles of Accounts');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 33, 'Additional Mathematics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 33, 'Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 33, 'Chemistry');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 34, 'Sociology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 34, 'Psychology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 34, 'History');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 34, 'Higher Malay');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 34, 'Mother Tongue');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 34, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 34, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 34, 'Design and Technology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 35, 'Business');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 35, 'Nursing');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 35, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 35, 'Principles of Accounts');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 35, 'Combined Science');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 35, 'Additional Mathematics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 35, 'Nutrition and Food Science');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 35, 'Music');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 36, 'Technology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 36, 'Sport');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 36, 'Law');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 36, 'Tamil Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 36, 'Geography');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 36, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 36, 'Malay Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 36, 'Higher Tamil');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 37, 'Humanities');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 37, 'Psychology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 37, 'History');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 37, 'Higher Malay');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 37, 'Electronics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 37, 'Nutrition and Food Science');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 37, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 37, 'Physical Education');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 38, 'Mathematics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 38, 'Biology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 38, 'Business');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 38, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 38, 'Malay Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 38, 'Chinese Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 38, 'Electronics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 38, 'Additional Mathematics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 39, 'Psychology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 39, 'History');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 39, 'Nursing');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 39, 'History');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 39, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 39, 'Design and Technology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 39, 'Higher Chinese');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 39, 'Biology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 40, 'Psychology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 40, 'Computing');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 40, 'Technology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 40, 'Geography');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 40, 'Nutrition and Food Science');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 40, 'Music');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 40, 'Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 40, 'Electronics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 41, 'Design');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 41, 'History');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 41, 'Sport');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 41, 'Art');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 41, 'Drama ');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 41, 'Design and Technology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 41, 'Additional Mathematics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 41, 'Literature');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 42, 'Chemistry');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 42, 'Psychology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 42, 'History');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 42, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 42, 'Combined Science');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 42, 'Malay Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 42, 'History');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 42, 'Physical Education');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 43, 'Business');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 43, 'Sociology');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 43, 'Design');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 43, 'Music');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 43, 'Chinese Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 43, 'Biology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 43, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 43, 'Higher Malay');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 44, 'Design');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 44, 'Engineering');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 44, 'Psychology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 44, 'Electronics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 44, 'Art');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 44, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 44, 'Biology');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 44, 'Geography');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 45, 'Literature');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 45, 'Art');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 45, 'Physics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 45, 'Geography');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 45, 'Chinese Literature');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 45, 'Nutrition and Food Science');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'C', NOW(), 45, 'Higher Malay');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 45, 'Additional Mathematics');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 46, 'Nursing');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 46, 'Law');
INSERT INTO studentacadinterest (createdat, interested, updatedat, student_id, interestname) VALUES (NOW(), TRUE, NOW(), 46, 'Mathematics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 46, 'Higher Tamil');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 46, 'Mother Tongue');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 46, 'Chemistry');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'A', NOW(), 46, 'Additional Mathematics');
INSERT INTO studentacadperformance (createdat, grade, updatedat, student_id, subjectname) VALUES (NOW(), 'B', NOW(), 46, 'Chinese Literature');
