INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (1, 'International Trade Specialist');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (1, 'Customs Broker');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (1, 'Export Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (2, 'Tourism Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (2, 'Resort Operations Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (2, 'Event Coordinator');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (3, 'Product Designer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (3, 'Graphic Designer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (3, 'Interior Designer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (4, 'Real Estate Agent');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (4, 'Property Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (4, 'Valuation Officer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (5, 'Aerospace Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (5, 'Aircraft Maintenance Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (5, 'Aviation Safety Officer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (29, 'Software Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (29, 'QA Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (29, 'System Administrator');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (33, 'Business Analyst');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (33, 'Marketing Executive');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (33, 'Sales Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (34, 'Operations Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (34, 'Supply Chain Specialist');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (34, 'Business Consultant');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (40, 'Operations Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (40, 'Supply Chain Specialist');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (40, 'Business Consultant');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (53, 'Software Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (53, 'QA Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (53, 'System Administrator');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (68, 'Software Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (68, 'QA Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (68, 'System Administrator');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (81, 'Financial Analyst');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (81, 'Investment Banker');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (81, 'Loan Officer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (96, 'Operations Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (96, 'Supply Chain Specialist');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (96, 'Business Consultant');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (117, 'Aerospace Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (117, 'Aircraft Maintenance Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (117, 'Aviation Safety Officer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (122, 'Financial Analyst');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (122, 'Investment Banker');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (122, 'Loan Officer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (146, 'Software Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (146, 'QA Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (146, 'System Administrator');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (158, 'Aerospace Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (158, 'Aircraft Maintenance Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (158, 'Aviation Safety Officer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (169, 'Operations Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (169, 'Supply Chain Specialist');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (169, 'Business Consultant');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (180, 'Accountant');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (180, 'Auditor');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (180, 'Tax Consultant');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (181, 'Operations Manager');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (181, 'Supply Chain Specialist');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (181, 'Business Consultant');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (186, 'Software Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (186, 'QA Engineer');
INSERT INTO course_careerprospect (course_id, careerprospect) VALUES (186, 'System Administrator');
